name: "Scheduled Action"

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Echo current time
        run: echo "Current time is $(date)"